services:
#  app:
#    environment:
#      - MOCKSERVER_BASE_URL=http://mockserver:1080
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - mynetwork

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - mynetwork

  mockserver:
    image: mockserver/mockserver
    container_name: mockserver
    ports:
      - "1080:1080"
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/mockserver.json
    volumes:
      - ./mockserver:/config
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
