springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
spring:
  application:
    name: Challenge
  data:
    redis:
      host: localhost
      port: 6379
mockserver:
  base-url: ${MOCKSERVER_BASE_URL:http://localhost:1080}
