springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:mydatabase}
    username: myuser
    password: secret
  application:
    name: Challenge
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      database: 0
      timeout: 2000
mockserver:
  base-url: ${MOCKSERVER_BASE_URL:http://localhost:1080}
