springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  application:
    name: Challenge
  data:
    redis:
      host: localhost
      port: 6379
mockserver:
  base-url: ${MOCKSERVER_BASE_URL:http://localhost:1080}
